services:
  driver-service:
    build: ./node
    volumes:
      - ./node:/app
      - /app/venv
    ports:
      - 5000:5000

  frontend-service:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - driver-service
