services:
  driver-service:
    build:
      context: ./node
      dockerfile: Dockerfile.driver
    volumes:
      - ./node:/app
      - /app/venv
    ports:
      - 5000:5000

  worker-service1:
    build:
      context: ./node
      dockerfile: Dockerfile.worker
    volumes:
      - ./node:/app
      - /app/venv
    ports:
      - 5001:5001
    environment:
      - PORT=5001
      - NAME=Worker_One
      - ADDR=http://worker-service1:5001
      - DRIVER_ADDR=http://driver-service:5000
    depends_on:
      - driver-service

  worker-service2:
    build:
      context: ./node
      dockerfile: Dockerfile.worker
    volumes:
      - ./node:/app
      - /app/venv
    ports:
      - 5002:5002
    environment:
      - PORT=5002
      - NAME=Worker_Two
      - ADDR=http://worker-service2:5002
      - DRIVER_ADDR=http://driver-service:5000
    depends_on:
      - driver-service

  frontend-service:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - driver-service
