services:
  driver-service:
    build: ./driver_node
    volumes:
      - ./driver_node:/app
      - /app/venv
    ports:
      - 5000:5000

  worker-service1:
    build: ./worker_node
    volumes:
      - ./worker_node:/app
      - /app/venv
    ports:
      - 5001:5001
    environment:
      - NAME=Worker_One
      - ADDR=http://worker-service1:5001
    depends_on:
      - driver-service

  # worker-service2:
  #   build: ./worker_node
  #   volumes:
  #     - ./worker_node:/app
  #     - /app/venv
  #   ports:
  #     - 5002:5001
  #   environment:
  #     - NAME=w_two

  # worker-service3:
  #   build: ./worker_node
  #   volumes:
  #     - ./worker_node:/app
  #     - /app/venv
  #   ports:
  #     - 5003:5001
  #   environment:
  #     - NAME=w_three

  frontend-service:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - driver-service
