FROM python:3.14.0a1-slim-bullseye
WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

EXPOSE 5000
COPY  ./static/default.csv /tmp/default.csv
CMD [ "python", "src/driver_app.py"]